TekstilTakipSistemiCore.UI/Controllers/UygulamaKullaniciController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TekstilTakipSistemiCore.DAL.Entities;
using TekstilTakipSistemiCore.DAL.Response;
using TekstilTakipSistemiCore.DATA.Context;
using TekstilTakipSistemiCore.UI.Models;

namespace TekstilTakipSistemiCore.UI.Controllers
{
    public class UygulamaKullaniciController : Controller
    {
        private readonly ProjectContext _context;
        public UygulamaKullaniciController(ProjectContext context)
        {
            _context = context;
        }
        public IActionResult UygulamaKullaniciTanimi(UygulamaKullanici kullanici, int id)
        {
            id = Convert.ToInt32(HttpContext.Session.GetInt32("id"));
            kullanici = _context.UygulamaKullanicilar.FirstOrDefault(x => x.Id == id);
            ViewBag.Name = kullanici.Ad.ToUpper();
            ViewBag.Surname = kullanici.Soyad.ToUpper();
            return View("UygulamaKullaniciTanimi", "_Layout");
        }

        [HttpPost]
        public IActionResult UygulamaKullaniciTanimi(string txtkullaniciadi, string txtad1, string txtsoyad, string txtsifre)
        {
            if (String.IsNullOrEmpty(txtkullaniciadi))
            {
                TempData["Message"] = "Lütfen tüm alanları doldurunuz...";
                TempData["Sonuc"] = 0;
                return View();
            }

            UygulamaKullanici kullanici = _context.UygulamaKullanicilar.FirstOrDefault(x => x.KullaniciAdi == txtkullaniciadi && x.Ad == txtsoyad);
            if (kullanici == null)
            {
                UygulamaKullanici _kullanici = new UygulamaKullanici();
                _kullanici.KullaniciAdi = txtkullaniciadi;
                _kullanici.Ad = txtad1;
                _kullanici.Soyad = txtsoyad;
                _kullanici.Sifre = txtsifre;
                _kullanici.OlusturmaZamani = DateTime.Now;
                _kullanici.AktifMi = true;

                _context.UygulamaKullanicilar.Add(_kullanici);
                _context.SaveChanges();

                TempData["Message"] = "Kayıt Başarılı";
                TempData["Sonuc"] = 1;
            }
            else
            {
                TempData["Message"] = "Sistemde daha önce kayıtlı.";
                TempData["Sonuc"] = 0;
            }

            return View();
        }

      
    }
}

TekstilTakipSistemiCore.UI/Views/UygulamaKullanici/UygulamaKullaniciTanimi.cshtml
@{
    ViewData["Title"] = "UygulamaKullaniciTanimi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
</head>
<body class="hold-transition sidebar-mini">
    <span id="Message" class="d-none">@TempData["Message"]</span>
    <span id="Sonuc" class="d-none">@TempData["Sonuc"]</span>

    <!-- Site wrapper -->

    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="container-fluid">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                        </div>
                        <div class="col-sm-6">

                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <form method="post" asp-action="UygulamaKullaniciTanimi" asp-controller="UygulamaKullanici">
                <section class="content">
                    <div class="col-md-12">
                        <div class="col-md-9">
                            <div class="card card-secondary">
                                <div class="card-header">
                                    <h3 class="card-title">Kullanıcı Tanım</h3>
                                </div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="inputName">Sicil No</label>
                                        <input type="text" name="txtkullaniciadi" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="inputName">Adı</label>
                                        <input type="text" name="txtad1" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="inputName">Soyadı</label>
                                        <input type="text" name="txtsoyad" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="inputDescription">Şifre</label>
                                        <input type="password" autocomplete="off" name="txtsifre" class="form-control">
                                    </div>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-9">
                            <button type="submit" class="btn btn-primary btn-sm float-right ng-binding" id="linkButton">Kaydet</button>
                        </div>
                    </div>

                </section>
            </form>
            <!-- /.content -->
        </div>
    </div>
    <script>
        $(document).ready(function () {
            var message = $('#Message').text();
            var sonuc = $('#Sonuc').text();
            if (message !== '') {
                if (sonuc == 1) {
                    toastr.success(message);
                    toastr.options = {
                        "timeOut": "5000"
                    }
                }
                else {
                    toastr.warning(message);
                    toastr.options = {
                        "timeOut": "5000"
                    }
                }
            }

        })
    </script>
</body>
</html>