TekstilTakipSistemiCore.UI/Controllers/KimliklendirmeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TekstilTakipSistemiCore.DAL.Entities;
using TekstilTakipSistemiCore.DAL.Response;
using TekstilTakipSistemiCore.DATA.Context;
using TekstilTakipSistemiCore.UI.Models;

namespace TekstilTakipSistemiCore.UI.Controllers
{
    public class KimliklendirmeController : Controller
    {
        private readonly ProjectContext _context;
        public KimliklendirmeController(ProjectContext context)
        {
            _context = context;
        }
        public IActionResult KimliklendirmeTanimi(UygulamaKullanici kullanici, int id)
        {
            id = Convert.ToInt32(HttpContext.Session.GetInt32("id"));
            kullanici = _context.UygulamaKullanicilar.FirstOrDefault(x => x.Id == id);
            ViewBag.Name = kullanici.Ad.ToUpper();
            ViewBag.Surname = kullanici.Soyad.ToUpper();
            return View("KimliklendirmeTanimi", "_Layout");
        }

        [HttpPost]
        public IActionResult KimliklendirmeTanimi(int mefrusatlist, string hasarAciklama, string etiketno)
        {
            if (String.IsNullOrEmpty(etiketno) || mefrusatlist == -1)
            {
                TempData["Message"] = "Lütfen tüm alanları doldurunuz...";
                TempData["Sonuc"] = 0;
                return View();
            }
            Kimliklendirme etiketkontrol = _context.Kimliklendirmeler.FirstOrDefault(x => x.EtiketNo == etiketno && x.AktifMi == true);
            if (etiketkontrol != null)
            {
                TempData["Message"] = "Bu etiket numarasına ait kimliklendirme işlemi daha önce yapılmıştır.";
                TempData["Sonuc"] = 0;
            }
            else
            {
                Kimliklendirme kimlik = _context.Kimliklendirmeler.FirstOrDefault(x => x.EtiketNo == etiketno && x.AktifMi == true && x.MefrusatId == mefrusatlist);

                if (kimlik == null)
                {
                    Kimliklendirme _kimlik = new Kimliklendirme();
                    _kimlik.MefrusatId = mefrusatlist;
                    _kimlik.HasarAciklama = hasarAciklama;
                    _kimlik.EtiketNo = etiketno;
                    _kimlik.OlusturmaZamani = DateTime.Now;
                    _kimlik.AktifMi = true;

                    _context.Kimliklendirmeler.Add(_kimlik);
                    _context.SaveChanges();

                    TempData["Message"] = "Kayıt Başarılı";
                    TempData["Sonuc"] = 1;
                }
            }

            return View();
        }

        public IActionResult KimliklendirmeListele(UygulamaKullanici kullanici, int id)
        {
            id = Convert.ToInt32(HttpContext.Session.GetInt32("id"));
            kullanici = _context.UygulamaKullanicilar.FirstOrDefault(x => x.Id == id);
            ViewBag.Name = kullanici.Ad.ToUpper();
            ViewBag.Surname = kullanici.Soyad.ToUpper();

            //List<KimliklendirmeListViewModel> kimliklist = new List<KimliklendirmeListViewModel>();
            var kimlik = (from a in _context.Kimliklendirmeler
                          join b in _context.Mefrusatlar on a.MefrusatId equals b.Id
                          where a.AktifMi == true
                          select new KimliklendirmeListViewModel
                          {
                              EtiketNo = a.EtiketNo,
                              HasarAciklama = a.HasarAciklama,
                              MefrusatTur = b.MefrusatTuru,

                          }).ToList();

            if (kimlik != null)
            {
                ViewData["Kimliklendirmeler"] = kimlik;
            }

            return View("KimliklendirmeListele", "_Layout");


        }
        [HttpPost]
        public IActionResult KimliklendirmeMefrusatListele()
        {
            List<MefrusatListViewModel> mefrusatList = new List<MefrusatListViewModel>();
            var query = (from mef in _context.Mefrusatlar
                         where mef.AktifMi == true
                         select new MefrusatListViewModel()
                         {
                             MefrusatId = mef.Id,
                             MefrusatTuru = mef.MefrusatTuru
                         }).ToList();
            if (query.Count != 0)
            {
                mefrusatList.AddRange(query);
            }
            return Json(mefrusatList);

        }
    }
}

TekstilTakipSistemiCore.UI/Views/Kimliklendirme/KimliklendirmeListele.cshtml
@{
    ViewData["Title"] = "KimliklendirmeListele";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    IEnumerable<KimliklendirmeListViewModel> Kimliklendirmeler = ViewData["Kimliklendirmeler"] as IEnumerable<KimliklendirmeListViewModel>;
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
<form method="get" asp-action="KimliklendirmeListele" asp-controller="Kimliklendirme">
 <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Kimliklendirme Listesi</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Etiket No</th>
                                    <th>Hasar Açıklama</th>
                                    <th>Mefruşat Türü</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Kimliklendirmeler)
                                {
                                    <tr>
                                        <td></td>
                                        <td>@item.EtiketNo</td>
                                        <td>@item.HasarAciklama</td>
                                        <td>@item.MefrusatTur</td>
                                    </tr>

                                }

                            </tbody>
                           
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
               
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
</form>

TekstilTakipSistemiCore.UI/Views/Kimliklendirme/KimliklendirmeTanimi.cshtml
@{
    ViewData["Title"] = "KimliklendirmeTanimi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>

</head>
<body class="hold-transition sidebar-mini">
    <span id="Message" class="d-none">@TempData["Message"]</span>
    <span id="Sonuc" class="d-none">@TempData["Sonuc"]</span>
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="container-fluid">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <form method="post" asp-action="KimliklendirmeTanimi" asp-controller="Kimliklendirme">
                <section class="content">
                    <div class="col-md-12">
                        <div class="col-md-9">
                            <div class="card card-secondary">
                                <div class="card-header">
                                    <h3 class="card-title">Kimliklendirme Tanım</h3>

                                    @*<div class="card-tools">
                                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                                <i class="fas fa-minus"></i>
                                            </button>
                                        </div>*@
                                </div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="inputName">Etiket No</label>
                                        <input type="text" name="etiketno" id="etiketno" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="inputName">Mefruşat Türü</label>
                                        <select id="mefrusatlist" name="mefrusatlist" class="form-control custom-select"></select>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputDescription">Açıklama</label>
                                        <textarea id="hasarAciklama" class="form-control" name="hasarAciklama"></textarea>
                                    </div>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                        </div>


                    </div>
                    <div class="col-md-12">
                        <div class="col-md-9">
                            <button type="submit" class="btn btn-primary btn-sm float-right ng-binding" onclick="kimliklendirmeKaydet()">Kaydet</button>
                            @*<a style="height: 35px; float:right; background-color: #007bff; color: white " href="#" onclick="kimliklendirmeKaydet()" class="btn m-btn m-btn--icon pull-right">
                                <span>
                                    <i class="la la-calendar-check-o"></i>
                                    <span>Kaydet</span>
                                </span>
                            </a>*@
                        </div>
                    </div>

                </section>
            </form>
            <!-- /.content -->
        </div>
    </div>
    <script>
        $(document).ready(function () {
            var message = $('#Message').text();
            var sonuc = $('#Sonuc').text();
            if (message !== '') {
                if (sonuc == 1) {
                    toastr.success(message);
                    toastr.options = {
                        "timeOut": "5000"
                    }
                }
                else {
                    toastr.warning(message);
                    toastr.options = {
                        "timeOut": "5000"
                    }
                }
            }

        })
    </script>
</body>
</html>
<script src="~/js/MefrusatListele/MefrusatListele.js"></script>
<script src="~/js/KimliklendirmeAlani/KimliklendirmeTanimlama.js"></script>