TekstilTakipSistemiCore.UI/Controllers/MefrusatController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TekstilTakipSistemiCore.DAL.Entities;
using TekstilTakipSistemiCore.DATA.Context;

namespace TekstilTakipSistemiCore.UI.Controllers
{
    public class MefrusatController : Controller
    {
        private readonly ProjectContext _context;
        public MefrusatController(ProjectContext context)
        {
            _context = context;
        }
        public IActionResult MefrusatTanimi(UygulamaKullanici kullanici, int id)
        {
            id = Convert.ToInt32(HttpContext.Session.GetInt32("id"));
            kullanici = _context.UygulamaKullanicilar.FirstOrDefault(x => x.Id == id);
            ViewBag.Name = kullanici.Ad.ToUpper();
            ViewBag.Surname = kullanici.Soyad.ToUpper();
            return View("MefrusatTanimi", "_Layout");
        }

        [HttpPost]
        public IActionResult MefrusatTanimi(string mefrusattur, string mefrusatkod)
        {
            if (String.IsNullOrEmpty(mefrusattur) || String.IsNullOrEmpty(mefrusatkod))
            {
                TempData["Message"] = "Lütfen tüm alanları doldurunuz...";
                TempData["Sonuc"] = 0;
                return View();
            }

            Mefrusat mefrusat = _context.Mefrusatlar.FirstOrDefault(x => x.MefrusatTuru == mefrusattur && x.MefrusatKodu == mefrusatkod);
            if (mefrusat == null)
            {
                Mefrusat _mefrusat = new Mefrusat();
                _mefrusat.MefrusatTuru = mefrusattur;
                _mefrusat.MefrusatKodu = mefrusatkod;
                _mefrusat.OlusturmaZamani = DateTime.Now;
                _mefrusat.AktifMi = true;

                _context.Mefrusatlar.Add(_mefrusat);
                _context.SaveChanges();

                TempData["Message"] = "Kayıt Başarılı";
                TempData["Sonuc"] = 1;
            }
            else
            {
                TempData["Message"] = "Sistemde daha önce kayıtlı.";
                TempData["Sonuc"] = 0;
            }

            return View();
        }
       
        public IActionResult MefrusatListele(UygulamaKullanici kullanici, int id)
        {
            id = Convert.ToInt32(HttpContext.Session.GetInt32("id"));
            kullanici = _context.UygulamaKullanicilar.FirstOrDefault(x => x.Id == id);
            ViewBag.Name = kullanici.Ad.ToUpper();
            ViewBag.Surname = kullanici.Soyad.ToUpper();


            List<Mefrusat> mefrusat = _context.Mefrusatlar.Where(x => x.AktifMi == true).ToList();
            if (mefrusat != null)
            {
                ViewData["Mefrusatlar"] = mefrusat;
            }

            return View("MefrusatListele", "_Layout");

        }
    }
}

TekstilTakipSistemiCore.UI/Views/Mefrusat/MefrusatListele.cshtml
@{
    ViewData["Title"] = "MefrusatListele";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    IEnumerable<Mefrusat> mefrusatlar = ViewData["Mefrusatlar"] as IEnumerable<Mefrusat>;
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
<form method="get" asp-action="MefrusatListele" asp-controller="Mefrusat" >
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Mefruşat Tanım Listesi</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Mefruşat Türü</th>
                        <th>Mefruşat Kodu</th>
                        <th>Oluşturulma Zamanı</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in mefrusatlar)
                    {
                        <tr>
                            <td></td>
                            <td>@item.MefrusatTuru</td>
                            <td>@item.MefrusatKodu</td>
                            <td>@item.OlusturmaZamani</td>
                        </tr>

                    }
                </tbody>
               
            </table>
        </div>
        <!-- /.card-body -->
    </div>

    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
</form>



<!--<form method="get" asp-action="MefrusatListele" asp-controller="Mefrusat">
    <div class="wrapper">
        <div class="container-fluid">
            <div class="col-12">
                <div class="card card-secondary">
                    <div class="card-header">
                        <h3 class="card-title">Mefruşat Tanım Listesi</h3>

                        <div class="card-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>-->
<!-- /.card-header -->
<!--<div class="card-body table-responsive p-0">
    <table class="table table-hover text-nowrap">
        <thead>
            <tr>
                <th>#</th>
                <th>Mefruşat Türü</th>
                <th>Mefruşat Kodu</th>
                <th>Oluşturulma Zamanı</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in mefrusatlar)
            {
                <tr>
                    <td></td>
                    <td>@item.MefrusatTuru</td>
                    <td>@item.MefrusatKodu</td>
                    <td>@item.OlusturmaZamani</td>
                </tr>

            }

        </tbody>
    </table>
</div>-->
<!-- /.card-body -->
<!--</div>-->
<!-- /.card -->
<!--</div>
        </div>
        </div>

</form>-->

TekstilTakipSistemiCore.UI/Views/Mefrusat/MefrusatTanimi.cshtml
@{
    ViewData["Title"] = "MefrusatTanimi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>

</head>
<body class="hold-transition sidebar-mini">
    <span id="Message" class="d-none">@TempData["Message"]</span>
    <span id="Sonuc" class="d-none">@TempData["Sonuc"]</span>

    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="container-fluid">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                        </div>
                        <div class="col-sm-6">
                         
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <form method="post" asp-action="MefrusatTanimi" asp-controller="Mefrusat">
                <section class="content">
                    <div class="col-md-12">
                        <div class="col-md-9">
                            <div class="card card-secondary">
                                <div class="card-header">
                                    <h3 class="card-title">Mefruşat Tanım</h3>

                                    @*<div class="card-tools">
                                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                                <i class="fas fa-minus"></i>
                                            </button>
                                        </div>*@
                                </div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="inputName">Mefruşat Türü</label>
                                        <input type="text" name="mefrusattur" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="inputDescription">Mefruşat Kodu</label>
                                        <input type="text" name="mefrusatkod" class="form-control">
                                    </div>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-9">
                            <button type="submit" class="btn btn-primary btn-sm float-right ng-binding" id="linkButton">Kaydet</button>
                        </div>
                    </div>

                </section>
            </form>
            <!-- /.content -->
        </div>
    </div>
    <script>
        $(document).ready(function () {
            var message = $('#Message').text();
            var sonuc = $('#Sonuc').text();
            if (message !== '') {
                if (sonuc == 1) {
                    toastr.success(message);
                    toastr.options = {
                        "timeOut": "5000"
                    }
                }
                else {
                    toastr.warning(message);
                    toastr.options = {
                        "timeOut": "5000"
                    }
                }
            }
            
        })
    </script>
</body>
</html>